### ISSUE TITLE
Qui est derrière ce projet, quel hôpital? Comment est sûr que le projet sera facilement accepté ?

### ISSUE THREAD

**Issue by vetsolution** [HospiBed/COVID19-bed-management#1]
Bonjour,
Votre projet peux être intéressant, mais quand vous dites : "Un prototype présentant le concept a été présenté, et accepté, à la condition qu’il soit sécurisé et que seul le personnel soignant y ait accès"
Qui a fait cette approbation? un hôpital ? plusieurs? Une organisation gouvernemental ?

Je pose cette question car c'est beau de developer un projet mais après il faut voir comment celui sera accepter et intégré par le monde hospitalier, et voir aussi s'il non pas déjà de tel outil.

Quand à la sécurisation, faire quelque chose de secure n'est pas trop compliqué, mais avoir les bons point de contact et  donner l'acces aux bonne personnes est une autres histoire.

**Comment by HospiBed** [comment]
Bonjour,

Nous restons volontairement vagues sur ce point pour des raisons de confidentialité. 
Un camarade médecin, face à la surcharge des lits aux urgences de son hôpital, a cherché une solution plus simple que les emails et le téléphone pour tranférer ses patients. Devant l'absence de solutions, il a fait appel à nous, jeune ingénieurs R&D, pour lancer ce projet. C'est effectivement donc beau de développer ce projet car il vient d'un besoin direct.

Le prototype a été créé puis présenté par ce médecin devant un groupement d'hôpitaux publics, qui souhaite utiliser cette solution en complément de leurs outils actuels, à condition qu'il soit sécurisé et hébergeable sur leurs serveurs.

Nous avons donc dans l'idée de créer un code Open Source, intégrable au mieux possible pour les centres hospitalier intéressés, en sachant que plusieurs hôpitaux sont déjà intéressés par le prototype.

Bien à vous et bonne journée,

Antonin
